#! /bin/bash 

# build过程容易假死，为避免这个问题，请在Build前作好如下准备
#    1）为WSL2设置内存上限为物理内存的一半
#    2）关闭其它所有程序
#    3）打开"任务管理 >> 性能" 监控是否假死
#    4) 为了dockerfile文件的通用性，dockerfile中没有为各种源设置国内镜像。 
#    5) 如果在国内，尽可能在早上6点时build，这个时候很快。 因为，中国的出口带宽有限，特别时晚上人多导致从国外进行网络下载慢。

# 如果使用podman，建议设置全局别名
#    sudo vim /etc/profile
#    alias sudo='sudo '
#    alias docker='podman'
# 此时建议执行 `. ./build`  而不是  `./build`

docker build -t chaoskey/pythonlab pythonlab

if [ $? -ne 0 ]; then
    echo "Build Failed!"
    return 1
fi

docker build -t chaoskey/julialab julialab

if [ $? -ne 0 ]; then
    echo "Build Failed!"
    return 1
fi

docker build -t chaoskey/scimllab scimllab

if [ $? -ne 0 ]; then
    echo "Build Failed!"
    return 1
fi

docker build -t chaoskey/gridaplab gridaplab

if [ $? -ne 0 ]; then
    echo "Build Failed!"
    return 1
fi

docker build -t chaoskey/firedrakelab firedrakelab

if [ $? -ne 0 ]; then
    echo "Build Failed!"
    return 1
fi

docker build -t chaoskey/fenicsxlab fenicsxlab

if [ $? -ne 0 ]; then
    echo "Build Failed!"
    return 1
fi

alias | grep podman
if [ "$?"x == x ]; then
    docker build -t chaoskey/fenicslab fenicslab
else
    # 确保容器中命令`run x11_audio`可以正常执行
    sudo docker build -t chaoskey/fenicslab fenicslab
fi

if [ $? -ne 0 ]; then
    echo "Build Failed!"
    return 1
fi

return 0

